(in-package #:cm)
(export '(aaron3pt
          aaron4pt
          abs-intv
          addaug-motive
          addaugs
          Add-Children-to-Open
          adddur-motive
          add-rests
          all-codewords
          all-combos
          all-contours-in-set
          all-craw
          all-craw-pe-pc
          all-figs
          all-partitions
          allrots
          allrowperms
          allrows
          allrows-bytype
          all-sections-with-dur
          all-strav
          all-subsequences
          allswaps
          alltransp
          alternate
          altriad-func1
          A*-Nodes-Stored
          any-eql
          any-lcm
          apply-across
          apply-perm
          arpegg
          array->list
          atkpts
          atx->durs
          au-contraire
          auto-1d
          autosim-primitive
          autotransp
          avg-chdpit
          avg-chd-sort
          avoidurs
          axis-inversion
          basechange-motive
          basic-contours
          basicrows
          basic-scontours
          beat-intersection
          bestmatch
          bestmatch-nondet
          bestpath
          best-tz-path
          best-tzpath-vector
          beta-choices
          bins-by-val
          bitswitch
          blips->slots
          bottomline
          bscoding
          build-csd
          build-down
          build-snake
          build-thru
          build-up
          bumpup
          bz-matx
          bzms-chain
          bzms-shadow
          bzmult-simple
          bz-taxipath
          canned-frags
          c-distance
          chain-contour-util
          c-hanoi
          c-hanoichain
          c-hanoicoding
          c-hanoimap
          c-hanoimoves
          chdheight
          chdinv-down
          chd-inversion
          chdinv-up
          chds->lines
          chds->ties
          check-permutations-end
          c-height
          choose-chain-start
          chooser
          chop-list
          chord-complement
          chordints
          chord-neighbors
          chrom
          c-idmove
          clearbends
          clip-hi
          clip-lo
          clone
          clones
          closest
          closest-mod
          closest-mod-list
          closest-to-inv
          cloudy
          code->durs
          codemap
          code->pairs
          code->slots
          codeweight
          codeword
          combine-motives
          combine-pits
          commonseg
          commonseg-freeze
          complement-codeword
          completionp
          concorde-edgeweights
          conjunct-fragments
          consmatch
          consn-p
          contains-seq
          contains-set
          contains-test
          containsv
          contour-chain
          contour-equiv
          contour-inversion
          convert-into-patt
          convert-into-randpatt
          cope-events-to-seq
          coprime?
          copylist
          copything
          correct-order
          correct-pitlist
          craw-add
          craw-conv
          craw-ints
          craw-melconversions
          craw-mult
          craw-pc
          craw-pe
          cresc
          csd-to-file
          ct-candidates
          ctone
          curved-durs
          curved-path
          cw->chord
          c-width
          cw->mode
          cw-rots
          deepfunc
          deepscans
          deepscan-test
          demultiplied-motive
          density->code
          Describe-Solution
          designline
          designrem
          dia
          diachrom
          diachrom-filt
          diachrom-sets
          diff-vals
          dim
          directions
          disjoint-sets
          distribute
          div-dur
          divver
          divvy-up
          dnbeats
          doubler
          downdur
          drumidi-in
          drunkvec
          dsym
          dur-density
          durfunc
          durs->code
          durs->motive
          durs->slots
          durs->tpvec
          durwarp
          durwarp-clump
          durweight
          each-distance
          embed
          embell-func
          embellpc-func
          embell-triad
          empty-codeword
          end-to-end
          end-with
          entropy
          Entry
          eql-summer
          erasedurs
          event-to-istatement
          every-pctransp
          expand
          expwarp
          extract
          extractdurs
          extract-intervals
          extract-list
          extract-pairs
          extract-patt
          factorial
          factors
          Failure
          fastspace
          fast-tact
          ferncyc
          ferney
          ferneys
          fernlist
          fernwarp
          field-mod12p
          fillin
          filt-by-melint
          filter
          filterpos
          find-tz-flip
          First-Open-Node
          fit-length
          fixreg
          fixrhythm
          flatp
          flatten
          flatter
          flip-contour
          floats->rats
          frag
          frags
          frasetree
          frasetree-pits
          freeze
          freq-harmonics
          freqmult
          freqwarp
          fromto
          fromto-and-back
          fromto-stepper
          full-codeword
          fullscan-cons-utility
          gap2cyclops
          gather-pits
          gather-strums
          gaussian-choices
          generic-branch
          generic-chain
          generic-links
          generic-nform-path
          generic-path
          gen-rgr
          gen-tz
          get-densities
          get-long-scans
          %get-powers
          %get-powers-of-2-3
          get-scans
          get-simplebeats
          get-x
          get-y
          give-contour-to-mel
          give-contour-to-set
          give-ntn-contour
          Goal?
          grandrows
          G-Value
          hanoi
          hanoichain
          hanoimap
          hanoimoves
          harmonics-down
          heap-mx
          heapvec
          held-lines
          heterophony
          hex-combi-p
          hex-combi-partner
          higherchord
          histplot
          hits->ints
          holes
          H-Value
          hz->keys
          hzwarp
          idmove
          ilm
          inbetween
          indices
          initial-codeword
          interlock
          intv
          inverse-codeword
          inverse-idx
          inverse-motive
          inversion
          invert-chd
          invert-dk
          invert-order
          ipm
          irm
          iso
          is-palindrome
          itranspvec
          ivec
          jumpy->smooth
          key-fm
          key-harmonics
          key-rm
          knockdown
          layout
          lcmdurs
          lcmdurs-list
          leapdur
          len-eql
          lenfit
          life1d
          life2d
          life2dgen
          lifecell
          like-flat
          line-from-mels
          list>
          list-complement
          listdist
          listdist-mod
          list-eql
          listinv
          listmax
          listmean
          listmin
          list-partitions
          list>place
          lists->e2e
          list<sort
          lists->ptp
          list-stepper
          listsub
          list>-util
          lm
          ln-modal
          lowerchord
          m5
          m7
          make-diff
          make-diff-func
          make-diff-inits
          Make-Initial-Node
          makelen-code
          make-list-from-file
          Make-Node
          makepatt
          make-poly
          make-scans
          make-ties
          make-ttmode
          make-updown
          make-updown-random
          make-vector-indexed
          make-verse
          mallal-doubler
          mallal-intdoubler
          match2lists
          matchreg
          matchreg-chds
          match-scan
          match-slots
          meldurs->rpts
          melint
          melint-count
          melint->line
          mel-stress
          menses
          merge-codewords
          merge-one-element
          merge-poly
          merge-sd
          merge-slots
          midifile-to-seq
          midi-in
          midi-in
          midi-in1
          midi-totalen
          midline
          minmax-filt
          minstartpit
          mintprobs
          mintwgt
          mjsevenths
          mjtriad
          mjtriad2
          mjtriads
          mod12
          mod12-collect
          modarea
          mode->chord
          modeheight
          mode-ids-for-lists
          mode-inflect
          mode-lowest
          mode-mod12p
          mode-motive
          modenums
          mode-octave
          modereg
          mode-rw-1to1
          mode-rw-idlist
          mode-size
          mode-steps
          mod-intv
          modlist
          modmult
          modsum
          morph-arpegg
          morph-arpg-pair
          motive-density
          motive->durs
          motiveplay
          mr
          mt-rhyareas
          mt-rhyvec
          mtrptlen
          mtspacef
          mts-subs
          multaug-motive
          multievent
          multiple-assoc
          multiplied-motive
          multquant
          multquant-atx
          mx-apply
          mxchain
          mxlist
          myhand
          nearest-mult
          nearest-pcform
          neighbor
          neighbor-compl
          neighbor-nodelist
          neighborsum
          nestp
          nextcons
          nextrichain
          nform-rgr-path
          Node-F-Value
          Node-Less-Than?
          no-nils
          non-matches
          nono-distribute
          nonret-motive?
          norests
          normal-form
          norpt
          norpt-rand
          norpt-randpatt
          norpt-weights
          not-flat
          not-mel
          not-too-poly
          nths
          ntn->clist
          ntn->clists
          numidi-in
          numidi-in1
          numidi-vin
          numidi-vin1
          octavespread
          oddities-atx
          oddities-len
          oddity-idx
          oddsvals
          ois
          onescode
          ones&twos
          ordered-merge
          ordered-partitions
          ornadurs
          otherhex
          otone-reg
          overlap
          overlap-pair
          pad-pitches
          pair-resultant
          pairs->pit5
          pairs->pit7
          pairs->ptp
          Parent
          parse-by-reg
          parse-irule
          parsereg
          partitions
          patt-to-sum
          pcsubset
          peanocoding
          perles
          permutation
          permutations
          permutations
          permutations-list
          permutelist
          pforms
          pick-by-val
          pick-stress
          pitenc5
          pitenc7
          pitenctz
          pitsdurs->atx
          pitseq
          pix
          place-by-mod12
          place-cantiles
          placedist
          placefrag-cantiles
          place-ids
          placereg
          places->codeword
          place-slots
          place-tiles
          playchds->lines
          playmids
          playmode
          play-mode
          play-sd
          playspears
          play-ties
          plists
          plot1d
          pm
          poisson->code
          poissonvec
          poly->slots
          poly-stress
          polystrums
          poly->sublists
          popin
          popout
          populate
          positions
          prebump
          prep-rhythms
          prime-factors
          primefilt
          primep
          proper-subsets
          proper-subsets
          prouhet
          ptcollect-util
          pt-down-modal
          ptp->lists
          ptp->pit5
          ptp->pit7
          ptp->pittz
          pt-up-modal
          q-star
          quantdurs
          quantdurs-patt
          quantize-motive
          quantran
          quantranplay
          quantranplot
          ran-choices
          ranchords
          rand01array
          rand-arpegg
          randchain
          randdur
          rand-fig
          randhexrow
          randmel
          random-chord
          random-codeword
          random-indices
          random-mode
          randrests
          randscaley
          randsteps
          randsteps-single
          randurs
          randvec
          range
          rangefit
          range-in-mode
          ranvec
          ranvec-beta
          ranvec-gaussian
          rarpegg
          recurz
          regs->ptp
          relgraph
          relgraph->durs
          relpos
          rel-prime?
          rel-primes
          remove-redundancy
          remove-rpts
          render-with-csd
          render-with-orc
          reorder-by-melint
          reorder-by-melint
          repeater
          replace-all
          replace-intv
          replace-path
          rescale-all
          rescale-durs
          rescale-keyharms
          rescale-q
          resclassvec
          resultant
          resultant-chain
          revoice
          rgr-alldim1
          rgrandchain
          rgr-assoc
          rgr-assoc-all
          rgr-branch
          rgrchain
          rgr-fmt
          rgr-path
          rgr-proset
          rgr-proset-all
          rgr-reset
          rgr-reset-all
          rgrtranslist
          rhytpairvec
          richain
          rm
          rotate-list
          rotations
          round-all
          rowperms-bytype
          rows-by-seglen
          rows-by-swap
          rpts->durs
          run-bmatch
          run-concorde
          rwgen
          rw-gens
          rwmangle
          rw-next
          rw-stepper
          ryte
          safesort
          same-diachrom
          same-shape
          scale-array
          scale-fspectrum-low
          scale-fspectrum-top
          scale-ptp
          scale-spectrum-low
          scale-spectrum-top
          scale-stepper
          scanons
          scan-simuls
          scf
          scontours
          scrunch
          sections
          seg-distance
          seglen-concorde-edgeweights
          seg-with-pit
          self-expand
          selfsim
          selfsimvec
          self-stretto
          self-tile
          seq-eql
          seq-eql-with-rests
          seq-to-lilypond
          seq-to-midifile
          seq-to-sco
          shade-into
          Show-Solution
          shuffdur
          shuffle-all
          shufflebymod
          siftout
          simpl-for-sco
          simplified-motive
          sis
          slonim
          slonim-expand
          slonim-path
          slonim-tt
          slots->code
          slots->durs
          slots->tpoints
          slowline
          smooth
          smooth->jumpy
          smoothlist
          smorph
          smorph-pair
          snake
          some-mode
          sort-by-start
          sort-by-width
          sort-every
          Sort-Open-List
          sort-to-other
          spacegrp->motive
          spacegrp->vecs
          spacereg
          spaceregchain
          spaceregchainraw
          spacereglist
          spawned-motive
          spearmels
          spear->slots
          splay
          splay-cmn
          splay-fb
          splay-pair
          splice2mels
          splice-mels
          splotter
          spsequence
          squeezedurs
          s-sim
          ssim?
          ssim-atklen
          s-sim->slots
          ssim-speeds
          ssim-totalen
          stack-by
          stack-can
          stack-down
          stack-up
          startingrestnum
          step-increm
          stepper
          stravrot
          stravrot-func
          strumfit
          strums
          stutlist
          stutter
          subcodes
          submotives
          subseq-branch
          subseq-freeze
          subseq-path
          subsequences
          subset-freeze
          subsets
          subsets-len
          subsets-len
          sum
          sum7-utility
          sum-across
          sum-across-all
          sumpatt
          sumsort
          sumsort-dn
          sumvec
          swap-concorde-edgeweights
          swapdrop-chain
          swap-path
          t5-func
          take-contour
          take-ntn-contour
          take-places
          take-poly
          takereg
          take-subcontours
          take-updown
          taxi-nodelist
          tempo-shape
          tendreg
          tentmap
          tentmaps
          thinout
          ties?
          tievec
          tightrows
          tiles014
          tiles015
          tiles016
          timefunc
          tintab
          tn-type
          tonnetz-func
          topline
          topsort
          topsort-dn
          topsumsort
          topsumsort-dn
          total-distances
          tplay
          tplay-fb
          tpoints
          translists
          transp
          transpair
          transplevel
          transp-min
          transp-mode
          transp-order
          transpose-matx
          transp-to
          transpvec
          traverse-pts
          tr-by-grp
          trichord-p
          trichord-p
          tricp
          trimatch
          tr-insert
          tritone-func
          trope
          truevals
          tsp-chords
          tzchain
          tzdims
          tzfactors->moves
          tzmin-sum
          tzpath-vector-len
          tzpath-vectors
          tzplay
          tzrandchain
          tzrandlist
          tzworthy
          udwn
          un-modal
          updown-conversions
          updown-fromto
          updown-opposite
          updown-random
          updur
          valbytime
          vec->list
          vector-shuffle
          velsplay
          verse-drops
          verse-swaps
          voiced-well
          voiced-well-keys
          vplay
          wavy
          wedge
          wedge-idx
          weighted-codeword
          whirl
          wiggle
          wiggle-to
          wigline
          write-output-to-file
          zigzag
          zigzag-by-size
          zigzag-narmour)
        :cm)
