            instr JackNote
            ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ichannel   	=			    p1 - 1
itime 	   	= 			    p2
iduration  	= 			    p3
ikey 	   	= 			    p4
ivelocity  	= 			    p5
ijunk       =               p6 + p7 + p8 + p9 + p10 + p11
            JackoNoteOut 	"midiout", ichannel, ikey, ivelocity
            ; print 		    itime, iduration, ichannel, ikey, ivelocity
            endin

