(load "~/quicklisp/setup.lisp")
(ql:quickload :weyl)
(require :asdf)
(asdf:load-system :nudruz)
(asdf:load-system :cm2)
(in-package :cm)

(defparameter major (new cm:mode :degrees '(c  d  e f  g  a  b c)))
(defparameter M (new cm:mode :degrees     '(c     e    g        )))
(print major)
(print M)
(defparameter CM (cm:transpose M 0))
(print CM)
(defparameter CSM (cm:transpose M 1))
(print CSM)
(print (cm:keynum 'a7 :through CSM))
(defparameter M9 (new cm:mode :degrees    '(c  d  e    g     b  c)))
(defparameter m9 (new cm:mode :degrees    '(c  d  ef    g     bf  c)))

(defparameter R (weyl:get-real-numbers))
(print R)
(defparameter chord-space (weyl:get-vector-space R 11))
(print chord-space)
(defparameter chord (weyl:make-element chord-space 0 0 0 0 0 0 0 0 0 0 1))
(print chord)
(defparameter transforms (weyl:get-matrix-space R))
;(print transforms)
(defparameter I (weyl:one-matrix transforms 11))
(print I)
(quit)