#!/bin/sh
# [Gedit Tool]
# Name=Build and install C++ program
# Input=document
# Output=output-panel
# Applicability=all
# Save-files=document
# Shortcut=<Primary><Super>b

~/playpen.py cpp-app $GEDIT_CURRENT_DOCUMENT_PATH
