#!/bin/sh
# [Gedit Tool]
# Name=Render Csound piece to audio
# Input=document
# Output=output-panel
# Applicability=all
# Save-files=document
# Languages=

~/playpen.py csd-audio $GEDIT_CURRENT_DOCUMENT_PATH
